---
title: Blog Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: posts
    permalink: "/:categories/:title"
email: viraj.chaudhary@apexure.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/blog"
url: https://virajchuaudhary.github.io
twitter_username: jekyllrb
github_username: jekyll
paginate: 2
paginate_path: "/page:num/"
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-redirect-from
- jekyll-sitemap
